/**
 * Typed wrappers around the Wails Go bindings.
 * The actual calls go through window.go.main.App (generated by `wails generate module`).
 * We keep this layer thin — just type-cast and forward.
 */

import type {
  Skill,
  Project,
  ProjectCandidate,
  Activation,
  ActivationFilter,
  ActivateRequest,
  ActivateResult,
  ResolveConflictRequest,
  RegisterProjectRequest,
  DoctorReport,
} from '@/types'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const go = (window as any).go?.main?.App

function call<T>(method: string, ...args: unknown[]): Promise<T> {
  if (!go) throw new Error('Wails runtime not available')
  return go[method](...args) as Promise<T>
}

export const api = {
  // Skills
  listSkills: () => call<Skill[]>('ListSkills'),

  // Projects
  listProjects: () => call<Project[]>('ListProjects'),
  registerProject: (req: RegisterProjectRequest) =>
    call<Project>('RegisterProject', req),
  scanCandidates: (roots: string[]) =>
    call<ProjectCandidate[]>('ScanCandidates', roots),
  confirmCandidate: (candidate: ProjectCandidate) =>
    call<Project>('ConfirmCandidate', candidate),
  deleteProject: (id: string) => call<void>('DeleteProject', id),

  // Activations
  listActivations: (filter: ActivationFilter) =>
    call<Activation[]>('ListActivations', filter),
  activate: (req: ActivateRequest) => call<ActivateResult>('Activate', req),
  deactivate: (id: number) => call<void>('Deactivate', id),
  resolveConflict: (req: ResolveConflictRequest) =>
    call<void>('ResolveConflict', req),

  // Doctor
  runDoctor: () => call<DoctorReport>('RunDoctor'),
}
