// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"
	"skill-manager/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSkillRepository creates a new instance of MockSkillRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillRepository {
	mock := &MockSkillRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillRepository is an autogenerated mock type for the SkillRepository type
type MockSkillRepository struct {
	mock.Mock
}

type MockSkillRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillRepository) EXPECT() *MockSkillRepository_Expecter {
	return &MockSkillRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockSkillRepository
func (_mock *MockSkillRepository) GetByID(ctx context.Context, id string) (domain.Skill, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Skill, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Skill); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Skill)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkillRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSkillRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSkillRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSkillRepository_GetByID_Call {
	return &MockSkillRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSkillRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockSkillRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSkillRepository_GetByID_Call) Return(skill domain.Skill, err error) *MockSkillRepository_GetByID_Call {
	_c.Call.Return(skill, err)
	return _c
}

func (_c *MockSkillRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (domain.Skill, error)) *MockSkillRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSkillRepository
func (_mock *MockSkillRepository) List(ctx context.Context) ([]domain.Skill, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Skill, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Skill); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkillRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSkillRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSkillRepository_Expecter) List(ctx interface{}) *MockSkillRepository_List_Call {
	return &MockSkillRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockSkillRepository_List_Call) Run(run func(ctx context.Context)) *MockSkillRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkillRepository_List_Call) Return(skills []domain.Skill, err error) *MockSkillRepository_List_Call {
	_c.Call.Return(skills, err)
	return _c
}

func (_c *MockSkillRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Skill, error)) *MockSkillRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectRepository creates a new instance of MockProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepository {
	mock := &MockProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockProjectRepository struct {
	mock.Mock
}

type MockProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectRepository) EXPECT() *MockProjectRepository_Expecter {
	return &MockProjectRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProjectRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProjectRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProjectRepository_Delete_Call {
	return &MockProjectRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProjectRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockProjectRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Delete_Call) Return(err error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) GetByID(ctx context.Context, id string) (domain.Project, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Project, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Project); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProjectRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProjectRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockProjectRepository_GetByID_Call {
	return &MockProjectRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProjectRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockProjectRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_GetByID_Call) Return(project domain.Project, err error) *MockProjectRepository_GetByID_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (domain.Project, error)) *MockProjectRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) List(ctx context.Context) ([]domain.Project, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Project, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Project); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProjectRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProjectRepository_Expecter) List(ctx interface{}) *MockProjectRepository_List_Call {
	return &MockProjectRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockProjectRepository_List_Call) Run(run func(ctx context.Context)) *MockProjectRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectRepository_List_Call) Return(projects []domain.Project, err error) *MockProjectRepository_List_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockProjectRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Project, error)) *MockProjectRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Save(ctx context.Context, p domain.Project) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Project) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockProjectRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Project
func (_e *MockProjectRepository_Expecter) Save(ctx interface{}, p interface{}) *MockProjectRepository_Save_Call {
	return &MockProjectRepository_Save_Call{Call: _e.mock.On("Save", ctx, p)}
}

func (_c *MockProjectRepository_Save_Call) Run(run func(ctx context.Context, p domain.Project)) *MockProjectRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Project
		if args[1] != nil {
			arg1 = args[1].(domain.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Save_Call) Return(err error) *MockProjectRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectRepository_Save_Call) RunAndReturn(run func(ctx context.Context, p domain.Project) error) *MockProjectRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActivationRepository creates a new instance of MockActivationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivationRepository {
	mock := &MockActivationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivationRepository is an autogenerated mock type for the ActivationRepository type
type MockActivationRepository struct {
	mock.Mock
}

type MockActivationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivationRepository) EXPECT() *MockActivationRepository_Expecter {
	return &MockActivationRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockActivationRepository
func (_mock *MockActivationRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActivationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockActivationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockActivationRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockActivationRepository_Delete_Call {
	return &MockActivationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockActivationRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockActivationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivationRepository_Delete_Call) Return(err error) *MockActivationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActivationRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockActivationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindConflict provides a mock function for the type MockActivationRepository
func (_mock *MockActivationRepository) FindConflict(ctx context.Context, skillID string, agent domain.Agent, projectID string) (*domain.Conflict, error) {
	ret := _mock.Called(ctx, skillID, agent, projectID)

	if len(ret) == 0 {
		panic("no return value specified for FindConflict")
	}

	var r0 *domain.Conflict
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Agent, string) (*domain.Conflict, error)); ok {
		return returnFunc(ctx, skillID, agent, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Agent, string) *domain.Conflict); ok {
		r0 = returnFunc(ctx, skillID, agent, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Conflict)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.Agent, string) error); ok {
		r1 = returnFunc(ctx, skillID, agent, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivationRepository_FindConflict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindConflict'
type MockActivationRepository_FindConflict_Call struct {
	*mock.Call
}

// FindConflict is a helper method to define mock.On call
//   - ctx context.Context
//   - skillID string
//   - agent domain.Agent
//   - projectID string
func (_e *MockActivationRepository_Expecter) FindConflict(ctx interface{}, skillID interface{}, agent interface{}, projectID interface{}) *MockActivationRepository_FindConflict_Call {
	return &MockActivationRepository_FindConflict_Call{Call: _e.mock.On("FindConflict", ctx, skillID, agent, projectID)}
}

func (_c *MockActivationRepository_FindConflict_Call) Run(run func(ctx context.Context, skillID string, agent domain.Agent, projectID string)) *MockActivationRepository_FindConflict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.Agent
		if args[2] != nil {
			arg2 = args[2].(domain.Agent)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockActivationRepository_FindConflict_Call) Return(conflict *domain.Conflict, err error) *MockActivationRepository_FindConflict_Call {
	_c.Call.Return(conflict, err)
	return _c
}

func (_c *MockActivationRepository_FindConflict_Call) RunAndReturn(run func(ctx context.Context, skillID string, agent domain.Agent, projectID string) (*domain.Conflict, error)) *MockActivationRepository_FindConflict_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockActivationRepository
func (_mock *MockActivationRepository) List(ctx context.Context, filter ActivationFilter) ([]domain.Activation, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Activation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ActivationFilter) ([]domain.Activation, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ActivationFilter) []domain.Activation); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Activation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ActivationFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockActivationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ActivationFilter
func (_e *MockActivationRepository_Expecter) List(ctx interface{}, filter interface{}) *MockActivationRepository_List_Call {
	return &MockActivationRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockActivationRepository_List_Call) Run(run func(ctx context.Context, filter ActivationFilter)) *MockActivationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ActivationFilter
		if args[1] != nil {
			arg1 = args[1].(ActivationFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivationRepository_List_Call) Return(activations []domain.Activation, err error) *MockActivationRepository_List_Call {
	_c.Call.Return(activations, err)
	return _c
}

func (_c *MockActivationRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter ActivationFilter) ([]domain.Activation, error)) *MockActivationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockActivationRepository
func (_mock *MockActivationRepository) Save(ctx context.Context, a domain.Activation) (domain.Activation, error) {
	ret := _mock.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 domain.Activation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Activation) (domain.Activation, error)); ok {
		return returnFunc(ctx, a)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Activation) domain.Activation); ok {
		r0 = returnFunc(ctx, a)
	} else {
		r0 = ret.Get(0).(domain.Activation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Activation) error); ok {
		r1 = returnFunc(ctx, a)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockActivationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - a domain.Activation
func (_e *MockActivationRepository_Expecter) Save(ctx interface{}, a interface{}) *MockActivationRepository_Save_Call {
	return &MockActivationRepository_Save_Call{Call: _e.mock.On("Save", ctx, a)}
}

func (_c *MockActivationRepository_Save_Call) Run(run func(ctx context.Context, a domain.Activation)) *MockActivationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Activation
		if args[1] != nil {
			arg1 = args[1].(domain.Activation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivationRepository_Save_Call) Return(activation domain.Activation, err error) *MockActivationRepository_Save_Call {
	_c.Call.Return(activation, err)
	return _c
}

func (_c *MockActivationRepository_Save_Call) RunAndReturn(run func(ctx context.Context, a domain.Activation) (domain.Activation, error)) *MockActivationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentAdapter creates a new instance of MockAgentAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentAdapter {
	mock := &MockAgentAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentAdapter is an autogenerated mock type for the AgentAdapter type
type MockAgentAdapter struct {
	mock.Mock
}

type MockAgentAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentAdapter) EXPECT() *MockAgentAdapter_Expecter {
	return &MockAgentAdapter_Expecter{mock: &_m.Mock}
}

// Agent provides a mock function for the type MockAgentAdapter
func (_mock *MockAgentAdapter) Agent() domain.Agent {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Agent")
	}

	var r0 domain.Agent
	if returnFunc, ok := ret.Get(0).(func() domain.Agent); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.Agent)
	}
	return r0
}

// MockAgentAdapter_Agent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Agent'
type MockAgentAdapter_Agent_Call struct {
	*mock.Call
}

// Agent is a helper method to define mock.On call
func (_e *MockAgentAdapter_Expecter) Agent() *MockAgentAdapter_Agent_Call {
	return &MockAgentAdapter_Agent_Call{Call: _e.mock.On("Agent")}
}

func (_c *MockAgentAdapter_Agent_Call) Run(run func()) *MockAgentAdapter_Agent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgentAdapter_Agent_Call) Return(agent domain.Agent) *MockAgentAdapter_Agent_Call {
	_c.Call.Return(agent)
	return _c
}

func (_c *MockAgentAdapter_Agent_Call) RunAndReturn(run func() domain.Agent) *MockAgentAdapter_Agent_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyGlobal provides a mock function for the type MockAgentAdapter
func (_mock *MockAgentAdapter) ApplyGlobal(ctx context.Context, activeSkills []domain.Skill) error {
	ret := _mock.Called(ctx, activeSkills)

	if len(ret) == 0 {
		panic("no return value specified for ApplyGlobal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Skill) error); ok {
		r0 = returnFunc(ctx, activeSkills)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentAdapter_ApplyGlobal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyGlobal'
type MockAgentAdapter_ApplyGlobal_Call struct {
	*mock.Call
}

// ApplyGlobal is a helper method to define mock.On call
//   - ctx context.Context
//   - activeSkills []domain.Skill
func (_e *MockAgentAdapter_Expecter) ApplyGlobal(ctx interface{}, activeSkills interface{}) *MockAgentAdapter_ApplyGlobal_Call {
	return &MockAgentAdapter_ApplyGlobal_Call{Call: _e.mock.On("ApplyGlobal", ctx, activeSkills)}
}

func (_c *MockAgentAdapter_ApplyGlobal_Call) Run(run func(ctx context.Context, activeSkills []domain.Skill)) *MockAgentAdapter_ApplyGlobal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.Skill
		if args[1] != nil {
			arg1 = args[1].([]domain.Skill)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentAdapter_ApplyGlobal_Call) Return(err error) *MockAgentAdapter_ApplyGlobal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentAdapter_ApplyGlobal_Call) RunAndReturn(run func(ctx context.Context, activeSkills []domain.Skill) error) *MockAgentAdapter_ApplyGlobal_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyProject provides a mock function for the type MockAgentAdapter
func (_mock *MockAgentAdapter) ApplyProject(ctx context.Context, project domain.Project, activeSkills []domain.Skill) error {
	ret := _mock.Called(ctx, project, activeSkills)

	if len(ret) == 0 {
		panic("no return value specified for ApplyProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Project, []domain.Skill) error); ok {
		r0 = returnFunc(ctx, project, activeSkills)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentAdapter_ApplyProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyProject'
type MockAgentAdapter_ApplyProject_Call struct {
	*mock.Call
}

// ApplyProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project domain.Project
//   - activeSkills []domain.Skill
func (_e *MockAgentAdapter_Expecter) ApplyProject(ctx interface{}, project interface{}, activeSkills interface{}) *MockAgentAdapter_ApplyProject_Call {
	return &MockAgentAdapter_ApplyProject_Call{Call: _e.mock.On("ApplyProject", ctx, project, activeSkills)}
}

func (_c *MockAgentAdapter_ApplyProject_Call) Run(run func(ctx context.Context, project domain.Project, activeSkills []domain.Skill)) *MockAgentAdapter_ApplyProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Project
		if args[1] != nil {
			arg1 = args[1].(domain.Project)
		}
		var arg2 []domain.Skill
		if args[2] != nil {
			arg2 = args[2].([]domain.Skill)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentAdapter_ApplyProject_Call) Return(err error) *MockAgentAdapter_ApplyProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentAdapter_ApplyProject_Call) RunAndReturn(run func(ctx context.Context, project domain.Project, activeSkills []domain.Skill) error) *MockAgentAdapter_ApplyProject_Call {
	_c.Call.Return(run)
	return _c
}

// CapabilityCheck provides a mock function for the type MockAgentAdapter
func (_mock *MockAgentAdapter) CapabilityCheck(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CapabilityCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentAdapter_CapabilityCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CapabilityCheck'
type MockAgentAdapter_CapabilityCheck_Call struct {
	*mock.Call
}

// CapabilityCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgentAdapter_Expecter) CapabilityCheck(ctx interface{}) *MockAgentAdapter_CapabilityCheck_Call {
	return &MockAgentAdapter_CapabilityCheck_Call{Call: _e.mock.On("CapabilityCheck", ctx)}
}

func (_c *MockAgentAdapter_CapabilityCheck_Call) Run(run func(ctx context.Context)) *MockAgentAdapter_CapabilityCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentAdapter_CapabilityCheck_Call) Return(err error) *MockAgentAdapter_CapabilityCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentAdapter_CapabilityCheck_Call) RunAndReturn(run func(ctx context.Context) error) *MockAgentAdapter_CapabilityCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectScanner creates a new instance of MockProjectScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectScanner {
	mock := &MockProjectScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectScanner is an autogenerated mock type for the ProjectScanner type
type MockProjectScanner struct {
	mock.Mock
}

type MockProjectScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectScanner) EXPECT() *MockProjectScanner_Expecter {
	return &MockProjectScanner_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function for the type MockProjectScanner
func (_mock *MockProjectScanner) Scan(ctx context.Context, roots []string) ([]ProjectCandidate, error) {
	ret := _mock.Called(ctx, roots)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 []ProjectCandidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]ProjectCandidate, error)); ok {
		return returnFunc(ctx, roots)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []ProjectCandidate); ok {
		r0 = returnFunc(ctx, roots)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ProjectCandidate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, roots)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectScanner_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockProjectScanner_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - roots []string
func (_e *MockProjectScanner_Expecter) Scan(ctx interface{}, roots interface{}) *MockProjectScanner_Scan_Call {
	return &MockProjectScanner_Scan_Call{Call: _e.mock.On("Scan", ctx, roots)}
}

func (_c *MockProjectScanner_Scan_Call) Run(run func(ctx context.Context, roots []string)) *MockProjectScanner_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectScanner_Scan_Call) Return(projectCandidates []ProjectCandidate, err error) *MockProjectScanner_Scan_Call {
	_c.Call.Return(projectCandidates, err)
	return _c
}

func (_c *MockProjectScanner_Scan_Call) RunAndReturn(run func(ctx context.Context, roots []string) ([]ProjectCandidate, error)) *MockProjectScanner_Scan_Call {
	_c.Call.Return(run)
	return _c
}
