// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binding} from '../models';
import {config} from '../models';

export function Activate(arg1:binding.ActivateRequestDTO):Promise<binding.ActivateResultDTO>;

export function ConfirmCandidate(arg1:binding.ProjectCandidateDTO):Promise<binding.ProjectDTO>;

export function CopySkill(arg1:binding.CopySkillRequestDTO):Promise<void>;

export function Deactivate(arg1:number):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSkill(arg1:binding.DeleteSkillRequestDTO):Promise<void>;

export function FixIssue(arg1:binding.DoctorIssueDTO):Promise<void>;

export function GetSettings():Promise<config.Settings>;

export function ListActivations(arg1:binding.ActivationFilterDTO):Promise<Array<binding.ActivationDTO>>;

export function ListAllSkills():Promise<Array<binding.AggregatedSkillDTO>>;

export function ListProjectSkills(arg1:string):Promise<Array<binding.SkillDTO>>;

export function ListProjects():Promise<Array<binding.ProjectDTO>>;

export function ListSkills():Promise<Array<binding.SkillDTO>>;

export function ReadSkillContent(arg1:string):Promise<string>;

export function RegisterProject(arg1:binding.RegisterProjectRequestDTO):Promise<binding.ProjectDTO>;

export function ResolveConflict(arg1:binding.ResolveConflictRequestDTO):Promise<void>;

export function RunDoctor():Promise<binding.DoctorReportDTO>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function ScanCandidates(arg1:Array<string>):Promise<Array<binding.ProjectCandidateDTO>>;

export function SelectDirectory():Promise<string>;
