// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1) {
  return window['go']['main']['App']['Activate'](arg1);
}

export function ConfirmCandidate(arg1) {
  return window['go']['main']['App']['ConfirmCandidate'](arg1);
}

export function CopySkill(arg1) {
  return window['go']['main']['App']['CopySkill'](arg1);
}

export function Deactivate(arg1) {
  return window['go']['main']['App']['Deactivate'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListActivations(arg1) {
  return window['go']['main']['App']['ListActivations'](arg1);
}

export function ListAllSkills() {
  return window['go']['main']['App']['ListAllSkills']();
}

export function ListProjectSkills(arg1) {
  return window['go']['main']['App']['ListProjectSkills'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function RegisterProject(arg1) {
  return window['go']['main']['App']['RegisterProject'](arg1);
}

export function ResolveConflict(arg1) {
  return window['go']['main']['App']['ResolveConflict'](arg1);
}

export function RunDoctor() {
  return window['go']['main']['App']['RunDoctor']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanCandidates(arg1) {
  return window['go']['main']['App']['ScanCandidates'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
